export enum AuditAction {
  LOGIN = 'LOGIN',
  LOGOUT = 'LOGOUT',
  REFRESH_TOKEN = 'REFRESH_TOKEN',
  REGISTER = 'REGISTER',

  SESSION_CREATED = 'SESSION_CREATED',
  SESSION_UPDATED = 'SESSION_UPDATED',
  SESSION_DELETED = 'SESSION_DELETED',

  GAME_ENTRY_CREATED = 'GAME_ENTRY_CREATED',
  GAME_ENTRY_UPDATED = 'GAME_ENTRY_UPDATED',
  GAME_ENTRY_DELETED = 'GAME_ENTRY_DELETED',
}
